/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShortcutRouteImport } from './routes/shortcut'
import { Route as Landing3RouteImport } from './routes/landing3'
import { Route as Landing2RouteImport } from './routes/landing2'
import { Route as Landing1RouteImport } from './routes/landing1'
import { Route as IndexRouteImport } from './routes/index'

const ShortcutRoute = ShortcutRouteImport.update({
  id: '/shortcut',
  path: '/shortcut',
  getParentRoute: () => rootRouteImport,
} as any)
const Landing3Route = Landing3RouteImport.update({
  id: '/landing3',
  path: '/landing3',
  getParentRoute: () => rootRouteImport,
} as any)
const Landing2Route = Landing2RouteImport.update({
  id: '/landing2',
  path: '/landing2',
  getParentRoute: () => rootRouteImport,
} as any)
const Landing1Route = Landing1RouteImport.update({
  id: '/landing1',
  path: '/landing1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing1': typeof Landing1Route
  '/landing2': typeof Landing2Route
  '/landing3': typeof Landing3Route
  '/shortcut': typeof ShortcutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing1': typeof Landing1Route
  '/landing2': typeof Landing2Route
  '/landing3': typeof Landing3Route
  '/shortcut': typeof ShortcutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/landing1': typeof Landing1Route
  '/landing2': typeof Landing2Route
  '/landing3': typeof Landing3Route
  '/shortcut': typeof ShortcutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/landing1' | '/landing2' | '/landing3' | '/shortcut'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/landing1' | '/landing2' | '/landing3' | '/shortcut'
  id: '__root__' | '/' | '/landing1' | '/landing2' | '/landing3' | '/shortcut'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Landing1Route: typeof Landing1Route
  Landing2Route: typeof Landing2Route
  Landing3Route: typeof Landing3Route
  ShortcutRoute: typeof ShortcutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shortcut': {
      id: '/shortcut'
      path: '/shortcut'
      fullPath: '/shortcut'
      preLoaderRoute: typeof ShortcutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing3': {
      id: '/landing3'
      path: '/landing3'
      fullPath: '/landing3'
      preLoaderRoute: typeof Landing3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing2': {
      id: '/landing2'
      path: '/landing2'
      fullPath: '/landing2'
      preLoaderRoute: typeof Landing2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing1': {
      id: '/landing1'
      path: '/landing1'
      fullPath: '/landing1'
      preLoaderRoute: typeof Landing1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Landing1Route: Landing1Route,
  Landing2Route: Landing2Route,
  Landing3Route: Landing3Route,
  ShortcutRoute: ShortcutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
